### ISSUE TITLE
Auto-Sync frequency to be configurable from login api

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#103]
Auto-Sync frequency to be configurable from login API.

- autoSync { "frequency": 900000 } // in milli seconds, optional field
- If autoSync.frequency is not found in login API , should fall back on default frequency 10 mins
- Make sure backwards compatibility is working as expected.

**Comment by apurvabisht97** [comment]
auto-sync frequency is added in backend . If auto-sync frequency we will get from backend then that frequency value will be considered for background job . when auto-sync frequency field is not present in backend then default 10 min will be considered for background job.
