### ISSUE TITLE
Sync Saral SDK changes to SaralSDK repository

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#105]
Sync Saral SDK changes to SaralSDK repository, test

**Comment by dileep-gadiraju** [comment]
Sync sdk code into https://github.com/Sunbird-Saral/react-native-saral-sdk

**Comment by dileep-gadiraju** [comment]
Use https://github.com/Sunbird-Saral/react-native-saral-sdk/tree/feature/sdk-newfeatures branch for committing the changes.

**Comment by apurvabisht97** [comment]
Sync sdk code changes from https://github.com/Sunbird-Saral/Project-Saral/tree/main/v1.0/frontend/SaralApp/android/saralsdk into https://github.com/Sunbird-Saral/react-native-saral-sdk has been done successfully . @arman-tdev
