### ISSUE TITLE
Skip checkbox for multi-student layout not visible on all the mobiles. Need a cosmetic change to make sure it's visible on all the mobiles.

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#125]
Skip checkbox for multi-student layout not visible on all the mobiles. Need a cosmetic change to make sure it's visible on all the mobiles.

**Comment by apurvabisht97** [comment]
skip checkbox for multi-student layout is visible on all the mobiles is fixed .
@navin9584
