### ISSUE TITLE
training data collection for handwritten digits 

### ISSUE THREAD

**Issue by apurvabisht97** [Sunbird-Saral/Project-Saral#135]

**Comment by dileep-gadiraju** [comment]
Layout soft copies from U.P production can be found @ https://drive.google.com/drive/folders/10_uVoCEEo6arw6eHc5Jk9BYwiPeTmnSs?usp=sharing. Please scan these with app and capture training data of digits.

**Comment by apurvabisht97** [comment]
training data for empty layout are stored in above link
