### ISSUE TITLE
MCQ options Requirement

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#189]
**MCQ options**: As students fill out responses in OMRs, they must be given the choice to choose one of four options (A, B, C, D). Saral should be able to collect the information on the basis of the option being darkened and cQube should be able to evaluate the option chosen and provide either 0 marks (wrong option) or ‘x’ marks (right option). UP and AS have expressed this requirement.

Each question can have different options in a single layout. For example
Q1 can have A,B,C,D,E as options
Q2 can have options as Y, N
Q3 can have 0,1,2,3,4
Q4 can have M,F

**Comment by apurvabisht97** [comment]
mcq option requirement is also completed.

**Comment by apurvabisht97** [comment]
there are 30 questions for 1 one student and all questions have different different options . student has to pick only one omr value .
