### ISSUE TITLE
Personal Details Layout generation , configuration , testing with Alphanumeric block letters support

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#251]
Personal Details Layout generation, configuration, testing with Alphanumeric block letters support

**Comment by apurvabisht97** [comment]
personal layout is configured in backend and it is supporting alphnumeric block letters . 
Personal layout is configured in schoolId:m001 . This will be visible in minimal mode and roi type is personal-details .
https://drive.google.com/file/d/1FwhxLIC7bZ7ddTYWpQ2Rav_XV_GeWAH0/view?usp=sharing
