### ISSUE TITLE
 Saral offline mode support

### ISSUE THREAD

**Issue by arman-tdev** [Sunbird-Saral/Project-Saral#258]
need to cache some api response in local storage.

1) use offline flag name from login api
2) except login rest of the API response to be cached

**Comment by dileep-gadiraju** [comment]
Login API response flag to enable offline mode.
If offline mode is enabled after login app should work offline.

Regular Mode:
  Navigations
  API Calls
   
Minimal Mode:
  Navigations
  API Calls

**Comment by apurvabisht97** [comment]
offline mode enhancement is done .
