### ISSUE TITLE
studentIdTrainingData is not working properly with multiple student case .

### ISSUE THREAD

**Issue by apurvabisht97** [Sunbird-Saral/Project-Saral#42]
When I am scanning multiple student id it is showing same studentIdTrainingData for all the students which I have scan .
Single student id is working as expected it is showing same studentIdTrainingData for the student .

**Comment by dileep-gadiraju** [comment]
@apurvabisht97 , as the PR is merged please add your comments and close this

**Comment by apurvabisht97** [comment]
When I am scanning multiple student id it is showing exact same training data which is present on the screen .
