### ISSUE TITLE
Exam questions,LO to be listed as popup page on Scan screen

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#47]
Exam questions,LO to be listed as popup page on Scan screen

Exam Structure:
            "questions": [
                {
                    "questionId": "1",
                    "indicatorTitle": "L0-1",
                    "questionMarks": "1"
                },
                {
                    "questionId": "2",
                    "indicatorTitle": "L0-2",
                    "questionMarks": "1"
                },
                {
                    "questionId": "3",
                    "indicatorTitle": "L0-3",
                    "questionMarks": "1"
                },
                {
                    "questionId": "4",
                    "indicatorTitle": "L0-4",
                    "questionMarks": "1"
                },
                {
                    "questionId": "5",
                    "indicatorTitle": "L0-5",
                    "questionMarks": "1"
                },
                {
                    "questionId": "6",
                    "indicatorTitle": "L0-6",
                    "questionMarks": "1"
                },
                {
                    "questionId": "7",
                    "indicatorTitle": "L0-7",
                    "questionMarks": "1"
                },
                {
                    "questionId": "8",
                    "indicatorTitle": "L0-8",
                    "questionMarks": "1"
                },
                {
                    "questionId": "9",
                    "indicatorTitle": "L0-9",
                    "questionMarks": "1"
                },
                {
                    "questionId": "10",
                    "indicatorTitle": "L0-10",
                    "questionMarks": "1"
                },
                {
                    "questionId": "11",
                    "indicatorTitle": "L0-11",
                    "questionMarks": "1"
                },
                {
                    "questionId": "12",
                    "indicatorTitle": "L0-12",
                    "questionMarks": "1"
                },
                {
                    "questionId": "13",
                    "indicatorTitle": "L0-13",
                    "questionMarks": "1"
                },
                {
                    "questionId": "14",
                    "indicatorTitle": "L0-14",
                    "questionMarks": "1"
                },
                {
                    "questionId": "15",
                    "indicatorTitle": "L0-15",
                    "questionMarks": "1"
                },
                {
                    "questionId": "16",
                    "indicatorTitle": "L0-16",
                    "questionMarks": "1"
                },
                {
                    "questionId": "17",
                    "indicatorTitle": "L0-17",
                    "questionMarks": "1"
                },
                {
                    "questionId": "18",
                    "indicatorTitle": "L0-18",
                    "questionMarks": "1"
                },
                {
                    "questionId": "19",
                    "indicatorTitle": "L0-19",
                    "questionMarks": "1"
                },
                {
                    "questionId": "20",
                    "indicatorTitle": "L0-20",
                    "questionMarks": "1"
                },
                {
                    "questionId": "21",
                    "indicatorTitle": "L0-21",
                    "questionMarks": "1"
                },
                {
                    "questionId": "22",
                    "indicatorTitle": "L0-22",
                    "questionMarks": "1"
                },
                {
                    "questionId": "23",
                    "indicatorTitle": "L0-23",
                    "questionMarks": "1"
                },
                {
                    "questionId": "24",
                    "indicatorTitle": "L0-24",
                    "questionMarks": "1"
                },
                {
                    "questionId": "25",
                    "indicatorTitle": "L0-25",
                    "questionMarks": "1"
                },
                {
                    "questionId": "26",
                    "indicatorTitle": "L0-26",
                    "questionMarks": "1"
                },
                {
                    "questionId": "27",
                    "indicatorTitle": "L0-27",
                    "questionMarks": "1"
                },
                {
                    "questionId": "28",
                    "indicatorTitle": "L0-28",
                    "questionMarks": "1"
                },
                {
                    "questionId": "29",
                    "indicatorTitle": "L0-29",
                    "questionMarks": "1"
                },
                {
                    "questionId": "30",
                    "indicatorTitle": "L0-30",
                    "questionMarks": "1"
                }
            ]

**Comment by apurvabisht97** [comment]
exam details pop up is available on continue scan screen .
