### ISSUE TITLE
Scan Status button on final scan screen to show scan status in local storage 

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#50]
Scan Status button on final scan screen to show scan status in local storage

**Comment by navin9584** [comment]
added button for scan status, 
make a seperate screen for scan status list

**Comment by apurvabisht97** [comment]
scan button added at continue scan page .Scan button includes the information of scanned data and share icon is also added in that where we can share the json data via email .
