### ISSUE TITLE
json marks data in local storage needs sharable for troubleshooting/training AI/ML models.

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#53]
json marks data in local storage needs sharable for troubleshooting/training AI/ML models.
On Scan Status screen , a share icon to be displayed on top so that json marks content can be shared with support team.

**Comment by dileep-gadiraju** [comment]
The below bug is pending for this feature.

https://github.com/Sunbird-Saral/Project-Saral/issues/67

**Comment by apurvabisht97** [comment]
with the help of share icon we are able to share the data which is present in local storage .
