### ISSUE TITLE
at class section level save status is showing wrong student list and save count is also coming wrong.

### ISSUE THREAD

**Issue by apurvabisht97** [Sunbird-Saral/Project-Saral#54]
This issue is 

body passed for saved scan API:- {
  "classId": "5",
  "subject": "Hindi",
  "fromDate": "29/09/2021",
  "schoolId": "up001",
  "page": 0,
  "downloadRes": false
}

expected body for saved scan API:-
{
  "classId": "5",
  "section": "D",
  "subject": "Hindi",
  "fromDate": "29/09/2021",
  "schoolId": "up001",
  "page": 0,
  "downloadRes": false
}

**Comment by navin9584** [comment]
this bug is fixed

**Comment by dileep-gadiraju** [comment]
@navin9584 , please raise PR and let apurva validate it. make sure you pull latest from v1-develop.

**Comment by apurvabisht97** [comment]
now at class section level save status is showing correct student list and save count is also coming correct
