### ISSUE TITLE
Saral App to collect failure logs and should be able to email to support team

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#56]
Saral App to collect failure logs and should be able to email to support team.

- All the handled failure logs have to be captured and stored internally. When logs cross a certain limit(to be decided), they can be cleared.
- When the user clicks the support icon shown on the top section of the app screens, it should open default email with logs in the body.

Refer mock design for Logout, Support to be shown as header:
https://xd.adobe.com/view/93744148-6c31-4e9b-aa33-f3cde3c19723-c627/
https://xd.adobe.com/view/66e79e70-7470-4ab0-a2b1-3db978f645fd-33b4/screen/1d2d1e50-55ea-4ca7-a9e5-d03556defb08/ 

https://drive.google.com/drive/folders/1VmcWyeZjwHvj7jUCSBstbO5BtD--Y-70

**Comment by navin9584** [comment]
added logout And support option on header

**Comment by dileep-gadiraju** [comment]
@navin9584 / @arman-tdev ,
look into the following issues:

- Pop down on header for support/logout options should close when a user does some other operations on the page.
- When there is API failure on the current page when you click on the support button on the same page, logs are not loaded. Only when you navigate to other page logs are updated. please look into it.

cc: @apurvabisht97

**Comment by apurvabisht97** [comment]
this issue is fixed whenever we are encountering failure logos we can send it to support team to trace the failure reason .
we have added this functionality on each page . And we have implemented logout also so that user can logout from any page . If you have scanned data in local and you try to logout it will push your data to backend .
