### ISSUE TITLE
not able to send email for local storage data when count is equal to or more than 10

### ISSUE THREAD

**Issue by apurvabisht97** [Sunbird-Saral/Project-Saral#67]
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 3041, "dt": 101529, "prevDt": 189040}

**Comment by navin9584** [comment]
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 3041, "dt": 101529, "prevDt": 189040}

**Comment by apurvabisht97** [comment]
able to send more than 10 student data  .
