### ISSUE TITLE
Multi-Tenant Branding: Enhance all the screens to externalize the labels 

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#86]
Multi-Tenant Branding: Enhance all the screens to externalize the labels

**Comment by dileep-gadiraju** [comment]
"navigationLabels":{
    "selectDetails":{
      "School": "Organisation",
      "SchoolId": "OrganisationId",
      "Class": "Category",
      "Section": "Skill"
    }
  }

**Comment by navin9584** [comment]
Test Cases 
1. login with new school :- skill001 & skill@123
2. organisation label and organisation Id label coming or not on every page on place of school & school Id
3. class label is replace by category , section label is replaced by skill and subject label is Skill Assesment
4. all the label coming from backend brand.json 
5. if label is not come from backend then default label is shown

**Comment by apurvabisht97** [comment]
multibranding labels is created as expected .
