### ISSUE TITLE
Swagger documentation issue

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#9]
Swagger documentation shows /login as api path instead of /schools/login. Please check other API paths also once and correct as needed.

**Comment by dileep-gadiraju** [comment]
@apurvabisht97 ,  /schools/login API response don't have below classes section. I want you to review each and every API both request / response and error messages and correct all documentation issues.

"classes": [
        {
            "sections": [
                {
                    "section": "D"
                },
                {
                    "section": "B"
                },
                {
                    "section": "C"
                }
            ],
            "classId": "2",
            "className": "Class-2"
        },
        {
            "sections": [
                {
                    "section": "D"
                },
                {
                    "section": "B"
                },
                {
                    "section": "C"
                }
            ],
            "classId": "3",
            "className": "Class-3"
        },
        {
            "sections": [
                {
                    "section": "D"
                },
                {
                    "section": "B"
                },
                {
                    "section": "C"
                }
            ],
            "classId": "4",
            "className": "Class-4"
        },
        {
            "sections": [
                {
                    "section": "D"
                },
                {
                    "section": "B"
                },
                {
                    "section": "C"
                }
            ],
            "classId": "5",
            "className": "Class-5"
        },
        {
            "sections": [
                {
                    "section": "D"
                },
                {
                    "section": "B"
                },
                {
                    "section": "C"
                }
            ],
            "classId": "6",
            "className": "Class-6"
        },
        {
            "sections": [
                {
                    "section": "D"
                },
                {
                    "section": "B"
                },
                {
                    "section": "C"
                }
            ],
            "classId": "7",
            "className": "Class-7"
        },
        {
            "sections": [
                {
                    "section": "D"
                },
                {
                    "section": "B"
                },
                {
                    "section": "C"
                }
            ],
            "classId": "8",
            "className": "Class-8"
        }
    ]

**Comment by apurvabisht97** [comment]
Sure

**Comment by dileep-gadiraju** [comment]
@apurvabisht97 ,

/saveMarks API request body subject field is missing. please recheck and add. Validate all the fields in APIs once again.

**Comment by apurvabisht97** [comment]
updated swagger doc with appropriate examples .
