### ISSUE TITLE
AutoSync enable/disable option in login API

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Project-Saral#93]
AutoSync enable/disable option in login API:

- Login API add optional autoSync boolean attribute. Make sure Saral App works even without this flag from the backend. By default, it should be set to false.
- Across Saral make sure AutoSync feature including auto sync validations are enabled/disabled using this flag.

**Comment by apurvabisht97** [comment]
background process will start only when login API receives autosync flag as true . otherwise when autosync flag is false and autosync field is missing from login API background process will not start .

**Comment by dileep-gadiraju** [comment]
@apurvabisht97 , why did you close this issue? its not yet implemented.
